# Configuration for 90% Probability Threshold Backtest
# Uses existing trained model - no retraining needed

symbol: "ETHUSDC"
timeframes: ["5m", "15m", "30m", "1h", "4h", "1d"]
base_timeframe: "15m"
lookback_years: 1
label_horizon_bars: 1

train:
  test_size: 0.2
  random_state: 42
  epochs: 20
  batch_size: 512
  lr: 0.001
  hidden_size: 128
  dropout: 0.2

backtest:
  fee_bps: 10        # 0.10% trading fee
  threshold: 0.90    # 90% probability threshold (ultra conservative)
  hold_bars: 1       # hold for 1 bar before selling

live:
  enabled: false
  poll_seconds: 30
  dry_run: true
  trade_quote_size: 25.0  # 25 USDC per trade

storage:
  data_dir: "./data"
  artifacts_dir: "./artifacts"

use_testnet: false  # Using live keys
