# Fast Start Live Trading Configuration
# Optimized for quick startup with minimal data requirements

symbol: "ETHUSDC"
timeframes: ["15m", "1h", "4h"]  # Reduced timeframes for faster startup
base_timeframe: "15m"
lookback_years: 0.5  # Reduced from 1 year to 6 months
label_horizon_bars: 1

train:
  test_size: 0.2
  random_state: 42
  epochs: 20
  batch_size: 512
  lr: 0.001
  hidden_size: 128
  dropout: 0.2

backtest:
  fee_bps: 10        # 0.10% trading fee
  threshold: 0.90    # 90% probability threshold
  hold_bars: 1       # hold for 1 bar before selling

live:
  enabled: true       # ENABLED for live trading
  poll_seconds: 30    # Check every 30 seconds
  dry_run: true       # START WITH DRY RUN (no real trades)
  trade_quote_size: 25.0  # 25 USDC per trade

storage:
  data_dir: "./data"
  artifacts_dir: "./artifacts"

use_testnet: false    # Using live Binance API
