# AiETHTrader Configuration File
# Copy this file and modify as needed, then use --config your_config.yaml

symbol: "ETHUSDC"
timeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"]
base_timeframe: "15m"
lookback_years: 2
label_horizon_bars: 1

train:
  test_size: 0.2
  random_state: 42
  epochs: 20
  batch_size: 512
  lr: 0.001
  hidden_size: 128
  dropout: 0.2

backtest:
  fee_bps: 10        # 0.10% trading fee
  threshold: 0.55    # probability threshold to enter long
  hold_bars: 1       # hold for N bars before selling

live:
  enabled: false
  poll_seconds: 30
  dry_run: true
  trade_quote_size: 50.0

storage:
  data_dir: "./data"
  artifacts_dir: "./artifacts"

use_testnet: true
