# Multi-Coin Live Trading Configuration
# Optimized for live trading with efficient data management for all coins

# Note: symbol is not used in multi-coin mode, coins are detected from artifacts
symbol: "MULTI_COIN"
timeframes: ["1h", "4h", "1d"]  # Focus on 1h with 4h/1d trends
base_timeframe: "1h"            # Primary trading timeframe
lookback_years: 2               # 2 years of historical data for models
label_horizon_bars: 1           # Predict next 1h bar

train:
  test_size: 0.2                # 20% for testing
  random_state: 42              # Reproducible results
  epochs: 50                    # More epochs for better learning
  batch_size: 256               # Smaller batch size for stability
  lr: 0.0005                    # Lower learning rate for stability
  hidden_size: 256              # Larger network for complex patterns
  dropout: 0.3                  # Higher dropout for regularization

backtest:
  fee_bps: 10                   # 0.10% trading fee
  threshold: 0.7                # 70% probability threshold for buy signals
  hold_bars: 1                  # Hold for exactly 1 bar (1 hour)
  min_gain_pct: 3.0             # Minimum 3% gain requirement

live:
  enabled: true                 # Enable live trading
  poll_seconds: 60              # Check every 60 seconds
  dry_run: true                 # START WITH DRY RUN (no real trades)
  trade_quote_size: 25.0        # 25 USDC per trade
  max_positions: 1              # Maximum 1 position at a time
  risk_management:
    max_daily_trades: 10        # Maximum trades per day
    max_drawdown: 0.1           # 10% maximum drawdown
    stop_loss_pct: 0.05         # 5% stop loss (if implemented)

storage:
  data_dir: "./data"
  artifacts_dir: "./artifacts"
  cache_dir: "./cache"          # Cache directory for live data

# Data management settings
data_management:
  cache_size_limits:
    "1h": 17520                 # 2 years of hourly data
    "4h": 4380                  # 2 years of 4-hour data
    "1d": 730                   # 2 years of daily data
  update_frequency: 3600        # Update every hour (3600 seconds)
  retry_attempts: 3             # Retry failed requests
  rate_limit_delay: 0.1         # Delay between API calls

# Exchange settings
exchange:
  use_testnet: true             # Use testnet for safety
  api_timeout: 30               # API timeout in seconds
  max_retries: 3                # Maximum retry attempts

# Logging settings
logging:
  level: "INFO"                 # Logging level
  file: "multi_coin_live_trading.log"  # Log file
  max_size: 10485760           # 10MB max log file size
  backup_count: 5              # Keep 5 backup log files
